### PR TITLE
Footer almost done

### PR DESCRIPTION
**Pull request by AngelVDev**
**To add**
- [x] Fonts
- [x] Fill the empty column
- [x] Final sizes adjustment

### CODE REVIEW

**Review by jeanpierre-jeri — COMMENTED** [review]
Se ve bien

**Review by jeanpierre-jeri — APPROVED** [review]

**Review by jioxel — COMMENTED** [review]
👌 nice

**Review by jioxel — APPROVED** [review]

**Comment by davidcoachdev** [comment]
super falta el carrusel de los dev

**Review by davidcoachdev — APPROVED** [review]
super

**Pull request merged**
